### ISSUE TITLE
Google CheckStyle

### ISSUE THREAD

**Issue by ChristopheCVB** [obs-websocket-community-projects/obs-websocket-java#104]
Apply Google CheckStyle on project

**Comment by TinaTiel** [comment]
XML for IntelliJ is available here: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml
And can be installed in `Settings > Editor > Code Style`

**Comment by ChristopheCVB** [comment]
We can easily do a code freeze and do it once and for all I think

**Comment by TinaTiel** [comment]
Yeah, that makes sense for timing -- will be a solid several hours of applying style updates, so making it a last task would make sense.

**Comment by ChristopheCVB** [comment]
![image](https://user-images.githubusercontent.com/946345/123705289-0ca05f80-d867-11eb-85a7-cf6e71f16f88.png)
Isn't that the automatic way of doing it?
