### ISSUE TITLE
Usage Examples

### ISSUE THREAD

**Issue by TinaTiel** [obs-websocket-community-projects/obs-websocket-java#108]
Rather than providing examples in the README, we could provide a small examples module/directory showing how to use the client for some common use cases:

- [x] Connect
- [x] Send a Request through convinience method
- [x] Send a Request through *Request class
- [x] Disconnect
- [x] Reconnect

- etc as requested (adding new examples could be tied directly to discussions or issues)

**Comment by ChristopheCVB** [comment]
We could then create a parent gradle module and add an example module alongside the existing one (being the client one)
