### ISSUE TITLE
Seems like there's no SetSceneItemProperties request, despite it being mentioned in the supported requests

### ISSUE THREAD

**Issue by RafatRifaie** [obs-websocket-community-projects/obs-websocket-java#115]
# Request Name
SetSceneItemProperties

# Additional Information
Looks like that request is only used to change the visibility of a source. I'd like to make changes to the transform of a source, and it's not currently possible.

**Comment by Pjiesco** [comment]
I guess you are talking about the current version 1.3.0.
We will not be updating this version anymore. As mentioned in the readme we will only be updating for websocket version v5. 
the next update for v5 will have this request

**Comment by RafatRifaie** [comment]
Will that include a fully functional SetSceneItemProperties request?

**Comment by ChristopheCVB** [comment]
> Will that include a fully functional SetSceneItemProperties request?

Yes, and all available requests too.

**Comment by ChristopheCVB** [comment]
In the meantime, feel free to fork the project and add whatever fields you want to SetSceneItemPropertiesRequest class

**Comment by ChristopheCVB** [comment]
You can also see the status of this library v2.0.0 [here](https://github.com/obs-websocket-community-projects/obs-websocket-java/milestone/1)

**Comment by RafatRifaie** [comment]
Thanks Chris, will try to my best hack it with my limited knowledge.
