### ISSUE TITLE
1.3.0 is not included in maven project

### ISSUE THREAD

**Issue by xiaoqiangkx** [obs-websocket-community-projects/obs-websocket-java#117]
![image](https://user-images.githubusercontent.com/1223296/131789855-82b324b6-a869-4465-8ac2-c7db57589790.png)
1.3.0 is not inclueded in https://mvnrepository.com/artifact/net.twasi/obs-websocket-java

**Comment by Pjiesco** [comment]
Please see [this](https://github.com/obs-websocket-community-projects/obs-websocket-java/issues/114#issuecomment-889019479)
