### ISSUE TITLE
Missing GetStats

### ISSUE THREAD

**Issue by quimodotcom** [obs-websocket-community-projects/obs-websocket-java#125]
# Request Name
GetStats

# Documentation
[Request Protocol Documentation](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getstats)

**Comment by ChristopheCVB** [comment]
This is implemented for v2.0.0 cf [GetStatsRequest](https://github.com/obs-websocket-community-projects/obs-websocket-java/blob/5.x.x/develop/client/src/main/java/io/obswebsocket/community/client/message/request/general/GetStatsRequest.java)
