### ISSUE TITLE
README ERROR

### ISSUE THREAD

**Issue by quimodotcom** [obs-websocket-community-projects/obs-websocket-java#126]
# Describe the bug
The link on the readme that directs to the maven repo is not functioning properly.

Please fix this link asap

Branch Mentioned: 5.x.x-develep

**Comment by ChristopheCVB** [comment]
It is the right link, it's just that there has been no release yet of v5.x

**Comment by quimodotcom** [comment]
> It is the right link, it's just that there has been no release yet of v5.x

ah right. would anyone be able to compile me one real quick???

**Comment by ChristopheCVB** [comment]
No, because it doesn't come right now because implementation is not finished. But feel free to give a hand and open a PR towards the release goal

**Comment by quimodotcom** [comment]
> No, because it doesn't come right now because implementation is not finished. But feel free to give a hand and open a PR towards the release goal

Np! I will happily lend a hand. Ill see what I can do!
