### ISSUE TITLE
Unable to Download via Gradle

### ISSUE THREAD

**Issue by Blade2021** [obs-websocket-community-projects/obs-websocket-java#131]
# Describe the bug
Using the suggested: 
```implementation 'io.obs-websocket.community:client:2.0.0'```

I'm unable to download the library.

# Expected behavior
Self explanatory.

# Additional context

This IS for the 2.0.0 version as I am attempting to use version 5 of the websocket.

**Comment by Blade2021** [comment]
![image](https://user-images.githubusercontent.com/1572869/168946476-71778ccb-21ce-4127-9a43-5e5920cb31e2.png)
Missing on MavenCentral as well.

**Comment by ChristopheCVB** [comment]
Hi there!
v2.0.0 hasn't been released yet.
We still have some work to finish, feel free to join us and open a PR ;)
