### ISSUE TITLE
Add support to manipulate TextGDI sources

### ISSUE THREAD

**Issue by ChristopheCVB** [obs-websocket-community-projects/obs-websocket-java#15]
Add the following Requests:
- GetTextGDIPlusProperties
- SetTextGDIPlusProperties

**Comment by DieserMerlin** [comment]
Feel free to make a PR

**Comment by TinaTiel** [comment]
protocols: 
https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#gettextgdiplusproperties
https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#settextgdiplusproperties

**Comment by TinaTiel** [comment]
May not get to this today -- but intend to work it, so I'll take ownership. 
Would like to do #30 first however

**Comment by ChristopheCVB** [comment]
Hey hello ! Happy new year ;)
Yes, I'm working on a fork in which I added multiple requests.
I will try to clean a little and then push it somewhere

**Comment by TinaTiel** [comment]
Phew! Glad I asked ;)
Looking forward to checking out the changes. 
If you haven't checked recently, btw, the Callback interface was generic-ified a bit. 
Also, I'm planning to also create an ObsClient interface and make the Controller implement it (so that later we could, hypothetically, create a StreamLabs OBSClient implementation).

**Comment by B1llstar** [comment]
Hi! I'm relatively new to Github. Has anybody found a solution to this problem? I currently have to read from a text file in OBS, and it is way way way slower than using a websocket.

**Comment by TinaTiel** [comment]
Unless @ChristopheCVB  has changed his mind, he plans to push this in at some point.

**Comment by ChristopheCVB** [comment]
I just need to find the time to do so :/

**Comment by TinaTiel** [comment]
here here XD
It's no problem, just wanted to check-in if you wanted to still work it. 
I've been super busy too lately, first time I've checked my email for a few weeks haha

**Comment by TinaTiel** [comment]
@B1llstar If you want to fork it sooner, it's mostly boilerplate stuff (nothing too complex) that involves:

- writing model classes
  - this project uses Gson for serialization/deserialization.
  - refer to https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md for what the (DTO) classes should look like 
- adding your class to the RequestType enum
- adding methods on both the ObsCommunicator and ObsRemoteController classes. 
    - methods take arguments (scene, source, etc) and a response callback
    - ObsCommunicator methods instantiate your DTOs, send them, and registers the callback by DTO type
    - ObsRemoteController wraps the ObsCommunicator methods

For example, the [SetTextGdiSources ](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#settextgdiplusproperties) method has `source`, `align`, `bk_color`, and dozens other properties. You might create a class like this:

```
package net.twasi.obsremotejava.requests.SetTextGDIPlusProperties

// snip

public class SetTextGDIPlusPropertiesRequest extends BaseRequest {

   private String source;
   private String align;

   @SerializedName("bk_color") // we need to explicitly tell Gson to send JSON that has a property like this
   private Integer bkColor; // Integer as opposed to int because this is an optional property according to the protocol

   // other properties

    public SetTextGDIPlusPropertiesRequest() {
        super(RequestType.SetTextGDIPlusPropertiesRequest);
    }

    // Getters and Setters
    // There's a f**k ton of them, consider a Fluent or a Builder pattern:
    SetTextGDIPlusPropertiesRequest bkColor(Integer bkColor) {
        this.bkColor = bkColor;
        return this;
    }

}
```

And then in the ObsRemoteController and ObsCommunicator classes you can copy the structure of one of the other methods:

```
// ObsCommunicator.java

    public void SetTextGDIPlusProperties(String source, String align, ...etc...., Callback<SetTextGDIPlusPropertiesRequest> callback) {
        SetTextGDIPlusPropertiesRequestrequest = new SetTextGDIPlusPropertiesRequest(...);
        session.getRemote().sendStringByFuture(new Gson().toJson(request));
        callbacks.put(SetTextGDIPlusPropertiesRequest.class, callback);
    }
```

**Comment by B1llstar** [comment]
Cool. I feel sort of silly that because I'm new to Github I don't know what
a fork is quite yet. I would imagine that means working on a feature for
somebody else's repository.

Thank you for the information! I will speak with my friend and mentor, and
see what we can come up with.

Bill

**Comment by TinaTiel** [comment]
It's no problem :)
The idea with a Fork is you create a copy of this repository on your account, work on it, and then when you're ready to push a feature you'll come back to the original repo (here) and make a PR from your Fork's branch into this repo's branch.

Good luck!

**Comment by B1llstar** [comment]
I wrote something that works (somehow)! I’ll submit a pull request tomorrow
after I clean a few things up and get approval from my friend who knows
better than I do.  I did pretty much exactly what you said, so thanks for
the advice! In the mean time, what’s the best way to deploy the new
features right now? Importing the repository is what I did before, but with
the new class files that wouldn’t include the new stuff.

Bill

**Comment by B1llstar** [comment]
I submitted a pull request (my first to a repository that wasn't my own) so
feel free to take a look! When you get a chance, I would like to know how I
can deploy this immediately. I'm a streamer myself working on a Twitch bot
project with a friend, and this functionality has immediate benefits.

**Comment by hsgarn** [comment]
Anyone able to complete this?

**Comment by TinaTiel** [comment]
I'm going to be starting looking into 5.X.X support in #40 , so probably not me. You're welcome to make a PR if you'd like (and Christophe has been contributing quite a bit too). Should follow these guidelines:

- Include both the get and set forms of the request
- Add some integration tests (see the ObsRemoteE2eObservationIT for examples)

But, keep in mind the 5.X.X is a big change to the API; this work would likely need to be redone when that comes out.

**Comment by ChristopheCVB** [comment]
Closing because v5.x has a completely different way to handle requests
