### ISSUE TITLE
OBSRemoteControler.disconnect doesn't stop the client

### ISSUE THREAD

**Issue by ChristopheCVB** [obs-websocket-community-projects/obs-websocket-java#156]

**Comment by nvdweem** [comment]
This is a bug/feature that I probably introduced.

The client isn't stopped because it will be reused when connect is called after disconnecting. `obsRemoteController.stop()` should currently stop the client.

**Comment by Pjiesco** [comment]
Yeah i think this is more a feature than a bug. This gives the option to reuse the client.

**Comment by ChristopheCVB** [comment]
Clients cannot be reused it seems
