### ISSUE TITLE
Automate Integration Tests via Container Tech

### ISSUE THREAD

**Issue by TinaTiel** [obs-websocket-community-projects/obs-websocket-java#18]
Currently Integration tests require the tester to manually run OBS and to enable/disable OBS Websocket authentication in OBS. 

This could be automated with any number of container technologies, an example is Docker and there are several OBS containers available that would do the job.

Not sure if it'd work in GH actions or not, but theoretically it could be possible to then setup CD on pushes to the repo once this is in place.

**Comment by LarsBaertschi** [comment]
I'll try to get this up and working! Also want to setup CD so it could be automatically validated.

**Comment by TinaTiel** [comment]
I took a look at https://hub.docker.com/r/bandi13/docker-obs but it uses the Linux version of OBS--which is sorely outdated.

Also took a look at using Docker to containerize Windows apps...Seems this is geared towards actually _building_ a Windows app from source into a container. 

So I guess the options would be either to:

- Build windows containers from the OBS source code, or
- Build a windows image and use a hypervisor etc to run it (not great for automation)

**Comment by TinaTiel** [comment]
@LarsBaertschi Did you ever get this working?

I tried taking  a look at it and found:

1. The official Windows images are for server, and
2. There are no official client images

I had the crazy thought to use VirtualBox running a Windows 10 image, all running inside a Docker container...which could work, but that would probably violate too many license agreements to ever be shared for e.g. automated testing. 

The main reason / problem I had was dealing with testing resources needing to be on absolute paths (also, env var expansion doesn't work), so my next thought in tackling this was to write a simple program to take an existing scene collection export and substitute file references. Then, provide the images, etc. needed for tests in a directory and running that program to substitute out the paths.

Thoughts?

**Comment by LarsBaertschi** [comment]
I tried this, and ran exactly into the issues you mentioned! So I really think we cannot fully test it end to end, the best possible thing would probably be to emulate the websocket server, but this is quite some effort. So I'm not really sure how to progress here. But your idea sounds quite promising! Would be excited to see if that actually works

**Comment by ChristopheCVB** [comment]
Or we could use a self hosted runner that has an OBS Instance running?

**Comment by TinaTiel** [comment]
@ChristopheCVB wouldn't that cost money?
Plus, we'd need to manage secrets in an OSS project like this (unless you want the public dirtying that environment) so that it stays 'clean'. But tbh even when under control within corp networks, I've personally not always had good experience with shared staging/testing environments unless they were destructible and rebuilt frequently. 

At that point, I'd think just using  a shared scene collection + resources would be simpler both from management and cost?

**Comment by TinaTiel** [comment]
Come to think of it, we might be able to get _some_ value out of using the Linux distro if the authentication stuff is the same. 
If we want to take the effort, using any of the existing containerized Linux distros of OBS with this plugin could be helpful there ...

**Comment by TinaTiel** [comment]
Great work on Christophe's part, getting a self-hosted runner working!
I'll keep this open so I can continue exploring the docker image route -- one consideration not brought up here yet is that OBS supposedly requires a GPU to run. I'm not sure if this will be the same for the Linux distro, it will need to be explored.

**Comment by TinaTiel** [comment]
It works!
https://github.com/obs-websocket-community-projects/obs-websocket-java/pull/85
https://github.com/TinaTiel/obs-websocket-docker
