### ISSUE TITLE
Add Java 9+ Support

### ISSUE THREAD

**Issue by rnayabed** [obs-websocket-community-projects/obs-websocket-java#24]
Please port this to Java Module System so that it can work with Java 9+

**Comment by TinaTiel** [comment]
@rnayabed I've personally not used Java Modules too much -- is there anything more to it than adding the package-info file, or are there other considerations?

**Comment by rnayabed** [comment]
> @rnayabed I've personally not used Java Modules too much -- is there anything more to it than adding the package-info file, or are there other considerations?
> 
> Or mayyybe you want to do this one / make a PR? (fork it, then make a PR from your fork)

I think you mean module-info.java :D
Well I have been working with java modules for a while (and you should too, java 8 is going to go EOL very soon)

**Comment by rnayabed** [comment]
Ill try seeing if I can add module support. But probably later because I am working on another project

**Comment by TinaTiel** [comment]
Haha, fair enough! 
I started my career writing plugins for Jira, pre Java 11 (up until recently they've only supported Java 8). 
Been using Java 11 on personal projects, but haven't yet run across an use case requiring modules since I do mostly Spring stuff atm.

**Comment by rnayabed** [comment]
> Haha, fair enough! I started my career writing plugins for Jira, pre Java 11 (up until recently they've only supported Java 8). Been using Java 11 on personal projects, but haven't yet run across an use case requiring modules since I do mostly Spring stuff atm.

Damn jira. I have only heard, never used it XD

**Comment by TinaTiel** [comment]
Lol, to be fair it's not inherently bad as a tool -- but it's a bit too flexible so in context folks tend to overuse it / use it where it doesn't belong. The one hammer to rule them all. 🔥🤣

**Comment by TinaTiel** [comment]
Noting a comment here -- if we're going to explicitly support / require Java 11, we should also upgrade the Jetty WebSocketClient

**Comment by ChristopheCVB** [comment]
I believe there are ways of importing a gradle dependency with Java 9
I think we will close this
