### ISSUE TITLE
Support OBS WebSocket 5.X

### ISSUE THREAD

**Issue by ChristopheCVB** [obs-websocket-community-projects/obs-websocket-java#40]
# Description
The 5.X version is approaching and is bringing breaking changes.

# Status
- Requests and Responses
    - General
        - [x] GetVersion
        - [x] BroadcastCustomEvent
        - [x] GetStats
        - [x] GetHotkeyList
        - [x] TriggerHotkeyByName
        - [x] TriggerHotkeyByKeySequence
        - [x] GetProjectorList
        - [x] OpenProjector
        - [x] CloseProjector
        - [x] GetStudioModeEnabled
        - [x] SetStudioModeEnabled
        - [x] Sleep
    - Config
        - [x] GetPersistentData
        - [x] SetPersistentData
        - [x] ~~GetGlobalPersistentData~~
        - [x] ~~SetGlobalPersistentData~~
        - [x] GetSceneCollectionList
        - [x] SetCurrentSceneCollection
        - [x] CreateSceneCollection
        - [x] RemoveSceneCollection
        - [x] GetProfileList
        - [x] SetCurrentProfile
        - [x] CreateProfile
        - [x] RemoveProfile
        - [x] GetProfileParameter
        - [x] SetProfileParameter
        - [x] ~~GetProfilePersistentData~~
        - [x] ~~SetProfilePersistentData~~
        - [x] GetVideoSettings
        - [x] SetVideoSettings
        - [x] GetStreamServiceSettings
        - [x] SetStreamServiceSettings
        - [ ] GetStreamBitrateSetting
        - [ ] SetStreamBitrateSetting
    - Sources
        - [ ] GetSourceList
        - [x] GetSourceActive
        - [x] GetSourceScreenshot
        - [x] SaveSourceScreenshot
    - Scenes
        - [x] GetSceneList
        - [x] GetCurrentProgramScene
        - [x] SetCurrentProgramScene
        - [x] GetCurrentPreviewScene
        - [x] SetCurrentPreviewScene
        - [x] CreateScene
        - [x] RemoveScene
        - [x] SetSceneName
        - [ ]  ~~SetSceneIndex~~
        - [x] GetSceneTransitionOverride
        - [x] SetSceneTransitionOverride
        - [x] DeleteSceneTransitionOverride
    - Inputs
        - [x] GetInputList
        - [x] CreateInput
        - [x] RemoveInput
        - [x] SetInputName
        - [x] GetInputKindList
        - [x] GetSpecialInputNames
        - [x] GetInputDefaultSettings
        - [x] GetInputSettings
        - [x] SetInputSettings
        - [x] GetInputMute
        - [x] SetInputMute
        - [x] ToggleInputMute
        - [x] GetInputVolume
        - [x] SetInputVolume
        - [x] GetInputAudioSyncOffset
        - [x] SetInputAudioSyncOffset
        - [x] GetInputTracks
        - [ ] SetInputTracks
        - [x] GetInputMonitorType
        - [x] SetInputMonitorType
        - [x] GetInputPropertiesListPropertyItems
        - [x] PressInputPropertiesButton
    - Transitions
        - [x] GetTransitionList
        - [x] GetCurrentTransition
        - [x] SetCurrentTransition
        - [ ] CreateTransition
        - [ ] RemoveTransition
        - [x] SetCurrentTransitionDuration
        - [x] GetTransitionSettings
        - [x] SetTransitionSettings
        - [x] ReleaseTbar
        - [x] SetTbarPosition
        - [x] TriggerStudioModeTransition
    - Filters
        - [x] GetSourceFilterList
        - [x] CreateSourceFilter
        - [x] RemoveSourceFilter
        - [ ] GetSourceFilterDefaultSettings
        - [x] GetSourceFilter
        - [x] SetSourceFilterIndex
        - [x] SetSourceFilterSettings
        - [x] SetSourceFilterEnabled
    - Scene Items
        - [x] GetSceneItemList
        - [x] GetGroupSceneItemList
        - [x] CreateSceneItem
        - [x] RemoveSceneItem
        - [x] DuplicateSceneItem
        - [x] GetSceneItemTransform
        - [x] SetSceneItemTransform
        - [x] GetSceneItemEnabled
        - [x] SetSceneItemEnabled
        - [x] GetSceneItemLocked
        - [x] SetSceneItemLocked
        - [ ] SetSceneItemColor
        - [x] GetSceneItemColor
        - [x] SetSceneItemIndex
    - Outputs
        - [ ] GetVirtualCamStatus
        - [ ] ToggleVirtualCam
        - [ ] StartVirtualCam
        - [ ] StopVirtualCam
        - [x] GetReplayBufferStatus
        - [x] ToggleReplayBuffer
        - [ ] StartReplayBuffer
        - [x] StopReplayBuffer
        - [x] SaveReplayBuffer
        - [x] GetLastReplayBufferReplay
        - [ ] GetReplayBufferTime
        - [ ] SetReplayBufferTime
        - [x] GetOutputList
        - [ ] GetOutputStatus
        - [x] ToggleOutput
        - [x] StartOutput
        - [x] StopOutput
        - [ ] GetOutputSettings
        - [ ] SetOutputSettings
    - Stream
        - [x] GetStreamStatus
        - [x] ToggleStream
        - [x] StartStream
        - [x] StopStream
        - [x] SendStreamCaption
    - Record
        - [x] GetRecordStatus
        - [x] ToggleRecord
        - [x] StartRecord
        - [x] StopRecord
        - [x] ToggleRecordPause
        - [x] PauseRecord
        - [x] ResumeRecord
        - [x] GetRecordDirectory
        - [x] SetRecordDirectory
        - [x] GetRecordFilenameFormatting
        - [x] SetRecordFilenameFormatting
    - Media Inputs
        - [x] GetMediaInputStatus
        - [x] OffsetMediaInputTimecode
        - [x] SetMediaInputTimecode
        - [x] SetMediaInputPauseState
        - [x] StopMediaInput
        - [x] RestartMediaInput
        - [x] NextMediaInputPlaylistItem
        - [x] PreviousMediaInputPlaylistItem
- Events
    - General
        - [x] ExitStarted
        - [x] StudioModeStateChanged
        - [x] CustomEvent
    - Config
        - [x] CurrentSceneCollectionChanged
        - [x] SceneCollectionListChanged
        - [x] CurrentProfileChanged
        - [x] ProfileListChanged
    - Scenes
        - [x] SceneCreated
        - [x] SceneRemoved
        - [x] SceneNameChanged
        - [x] ~~CurrentSceneChanged~~
        - [x] CurrentProgramSceneChanged
        - [x] CurrentPreviewSceneChanged
        - [x] SceneListChanged
    - Inputs
        - [x] InputCreated
        - [x] InputRemoved
        - [x] InputNameChanged
        - [x] InputMuteStateChanged
        - [x] InputVolumeChanged
        - [x] InputAudioSyncOffsetChanged
        - [x] InputAudioTracksChanged
    - Transitions
        - [ ] TransitionCreated
        - [ ] TransitionRemoved
        - [ ] TransitionNameChanged
        - [ ] CurrentTransitionChanged
        - [ ] TransitionStarted
        - [ ] TransitionEnded
    - Filters
        - [ ] FilterCreated
        - [ ] FilterRemoved
        - [ ] FilterNameChanged
        - [ ] SourceFilterAdded
        - [ ] SourceFilterRemoved
        - [ ] SourceFilterListReindexed
    - Outputs
        - [x] StreamStateChanged
        - [x] RecordStateChanged
        - [x] ReplayBufferStateChanged
        - [x] VirtualcamStateChanged
        - [x] ReplayBufferSaved
    - Scene Items
        - [x] SceneItemCreated
        - [x] SceneItemRemoved
        - [x] SceneItemListReindexed
        - [x] SceneItemEnableStateChanged
        - [x] SceneItemLockStateChanged
        - [ ] SceneItemTransformChanged
    - Media Inputs
        - [x] MediaInputPlaybackStarted
        - [x] MediaInputPlaybackEnded
        - [x] MediaInputActionTriggered
    - High Volume
        - [x] InputVolumeMeters
        - [x] InputActiveStateChanged
        - [x] InputShowStateChanged

**Comment by TinaTiel** [comment]
Sounds wise, though I'm wondering how/where you got it? 
I don't see any branches or tags on https://github.com/Palakis/obs-websocket/branches for 5.X 
Any other info on what these breaking changes are?

**Comment by TinaTiel** [comment]
Nvm: Found the notice: https://github.com/Palakis/obs-websocket/releases/tag/4.9.1

**Comment by TinaTiel** [comment]
And the protocol: https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md

**Comment by TinaTiel** [comment]
FYI @ChristopheCVB I've asked @DieserMerlin and @Blechkelle if we're going to state support for 5.X.X or not. I've joined the Discord and will check this out at least, looks like all the DTOs will need a rewrite and possibly the authentication process to an extent too...

**Comment by ChristopheCVB** [comment]
> Sounds wise, though I'm wondering how/where you got it?
> I don't see any branches or tags on https://github.com/Palakis/obs-websocket/branches for 5.X
> Any other info on what these breaking changes are?

@tt2468 sent it in the Touch Portal discord today

**Comment by TinaTiel** [comment]
@DieserMerlin  or @ChristopheCVB  any possibility we could add Christophe as a contributor to the repo?

**Comment by TinaTiel** [comment]
@ChristopheCVB How would you like to approach this? We could create a 5.X.X branch here and work against it on that branch (esp if we make you a contributor). Otherwise in the meantime I think we could work together on your private repo (you'd need to add me) and make a PR later to merge those changes in. Lemme know if you have a preference.

**Comment by ChristopheCVB** [comment]
This is an old list of Request. Closing it in favor of https://github.com/obs-websocket-community-projects/obs-websocket-java/pull/137
