### ISSUE TITLE
5.x Identify.rpcVersion

### ISSUE THREAD

**Issue by ChristopheCVB** [obs-websocket-community-projects/obs-websocket-java#53]
https://github.com/Twasi/websocket-obs-java/blob/7c720047ea46845561ca7de5024fc159ce4e0698/src/main/java/net/twasi/obsremotejava/OBSCommunicator.java#L249

I'm not sure we should use the rpcVersion returned by  the Hello message.
This is the rpcVersion our library supports, thus, it should be a constant.
As of now, there is only one rpcVersion (which is 1) but that might change in the future.

**Comment by TinaTiel** [comment]
Let's go for it.
Probably better to fail fast in that case
