### ISSUE TITLE
Requests Unit Tests

### ISSUE THREAD

**Issue by Pjiesco** [obs-websocket-community-projects/obs-websocket-java#74]
- General
    - [x] GetVersion
    - [x] BroadcastCustomEvent
    - [x] GetSystemStats
    - [x] GetHotkeyList
    - [x] TriggerHotkeyByName
    - [x] TriggerHotkeyByKeySequence
    - [x] GetProjectorList
    - [x] OpenProjector
    - [x] CloseProjector
    - [x] GetStudioModeEnabled
    - [x] SetStudioModeEnabled
    - [x] Sleep
- Config
    - [x] ~~GetGlobalPersistentData~~
    - [x] ~~SetGlobalPersistentData~~
    - [x] GetPersistentData
    - [x] SetPersistentData
    - [x] GetSceneCollectionList
    - [x] SetCurrentSceneCollection
    - [x] CreateSceneCollection
    - [x] RemoveSceneCollection
    - [x] GetProfileList
    - [ ] SetCurrentProfile
    - [x] GetProfileParameter
    - [x] SetProfileParameter
    - [x] ~~GetProfilePersistentData~~
    - [x] ~~SetProfilePersistentData~~
    - [ ] CreateProfile
    - [ ] RemoveProfile
    - [x] GetVideoSettings
    - [ ] SetVideoSettings
- Sources
    - [ ] GetSourceList
    - [x] GetSourceActive
    - [x] GetSourceScreenshot
    - [x] SaveSourceScreenshot
- Scenes
    - [x] GetSceneList
    - [x] GetCurrentProgramScene
    - [x] SetCurrentProgramScene
    - [x] GetCurrentPreviewScene
    - [x] SetCurrentPreviewScene
    - [x] SetSceneIndex
    - [x] SetSceneName
    - [x] CreateScene
    - [x] RemoveScene
    - [x] GetSceneTransitionOverride
    - [x] SetSceneTransitionOverride
    - [x] DeleteSceneTransitionOverride
- Inputs
    - [x] GetInputList
    - [x] GetInputKindList
    - [ ] GetSpecialInputNames
    - [x] GetInputDefaultSettings
    - [x] GetInputSettings
    - [x] SetInputSettings
    - [x] GetInputMute
    - [x] SetInputMute
    - [x] ToggleInputMute
    - [x] GetInputVolume
    - [x] SetInputVolume
    - [ ] GetInputAudioSyncOffset
    - [ ] SetInputAudioSyncOffset
    - [x] GetInputTracks
    - [ ] SetInputTracks
    - [x] GetInputMonitorType
    - [x] SetInputMonitorType
    - [ ] GetInputPropertiesListPropertyItems
    - [ ] PressInputPropertiesButton
    - [x] SetInputName
    - [x] CreateInput
    - [x] RemoveInput
- Transitions
    - [x] GetTransitionList
    - [x] GetCurrentTransition
    - [x] SetCurrentTransition
    - [x] SetCurrentTransitionDuration
    - [ ] GetTransitionSettings
    - [x] SetTransitionSettings
    - [x] ReleaseTbar
    - [x] SetTbarPosition
    - [x] TriggerStudioModeTransition
    - [ ] CreateTransition
    - [ ] RemoveTransition
- Filters
    - [x] GetSourceFilterList
    - [ ] GetSourceFilterDefaultSettings
    - [x] GetSourceFilter
    - [ ] SetSourceFilterIndex
    - [x] SetSourceFilterSettings
    - [x] SetSourceFilterEnabled
    - [x] CreateSourceFilter
    - [x] RemoveSourceFilter
- Scene Items
    - [x] GetSceneItemList
    - [ ] GetGroupSceneItemList
    - [ ] GetSceneItemTransform
    - [ ] SetSceneItemTransform
    - [x] GetSceneItemEnabled
    - [x] SetSceneItemEnabled
    - [x] GetSceneItemLocked
    - [x] SetSceneItemLocked
    - [x] GetSceneItemColor
    - [ ] SetSceneItemColor
    - [x] SetSceneItemIndex
    - [x] CreateSceneItem
    - [x] RemoveSceneItem
    - [x] DuplicateSceneItem
- Outputs
    - [ ] GetVirtualCamStatus
    - [ ] ToggleVirtualCam
    - [ ] StartVirtualCam
    - [ ] StopVirtualCam
    - [x] GetReplayBufferStatus
    - [x] ToggleReplayBuffer
    - [ ] StartReplayBuffer
    - [x] StopReplayBuffer
    - [x] SaveReplayBuffer
    - [x] GetLastReplayBufferReplay
    - [ ] GetReplayBufferTime
    - [ ] SetReplayBufferTime
    - [x] GetOutputList
    - [ ] GetOutputStatus
    - [x] ToggleOutput
    - [x] StartOutput
    - [x] StopOutput
    - [ ] GetOutputSettings
    - [ ] SetOutputSettings
- Stream
    - [x] GetStreamStatus
    - [x] ToggleStream
    - [x] StartStream
    - [x] StopStream
    - [x] SendStreamCaption
    - [ ] GetStreamBitrateSetting
    - [ ] SetStreamBitrateSetting
    - [x] GetStreamServiceSettings
    - [x] SetStreamServiceSettings
- Record
    - [x] GetRecordStatus
    - [x] ToggleRecord
    - [x] StartRecord
    - [x] StopRecord
    - [x] ToggleRecordPause
    - [x] PauseRecord
    - [x] ResumeRecord
    - [x] GetRecordDirectory
    - [x] SetRecordDirectory
    - [x] GetRecordFilenameFormatting
    - [x] SetRecordFilenameFormatting
- Media Inputs
    - [x] GetMediaInputStatus
    - [x] OffsetMediaInputTimecode
    - [x] SetMediaInputTimecode
    - [x] SetMediaInputPauseState
    - [x] StopMediaInput
    - [x] RestartMediaInput
    - [x] NextMediaInputPlaylistItem
    - [x] PreviousMediaInputPlaylistItem

**Comment by ChristopheCVB** [comment]
@Pjiesco Can you update thie issue with a checklist that we can track?

**Comment by ChristopheCVB** [comment]
> @Pjiesco Can you update thie issue with a checklist that we can track?

Done, disregard my comment

**Comment by ChristopheCVB** [comment]
This is an old list of Request. Closing it in favor of #137
